"""Post-launch review report: renders a ReleaseScore as Markdown."""
from __future__ import annotations

from .models import Release
from .scoring import ReleaseScore

VERDICT_LABEL = {
    "hit": "HIT",
    "marginal": "MARGINAL",
    "miss": "MISS",
    "no-data": "NO DATA",
}


def render_report(release: Release, result: ReleaseScore) -> str:
    lines = [
        f"# Post-launch review: {release.name} ({release.version})",
        "",
        f"- **Release:** {release.name} `{release.id}`",
        f"- **Version:** {release.version}",
        f"- **Ship date:** {release.ship_date}",
        f"- **Owner:** {release.owner}",
        f"- **Overall score:** {result.score if result.score is not None else 'n/a'}% "
        f"of target",
        f"- **Verdict:** {VERDICT_LABEL[result.verdict]}",
        "",
        "## Hypothesis",
        "",
        release.hypothesis,
        "",
        "## Metric results",
        "",
        "| Metric | Target | Observed | % of target | Verdict |",
        "| --- | --- | --- | --- | --- |",
    ]
    for m in result.metrics:
        observed = f"{m.observed:.2f}" if m.observed is not None else "n/a"
        pct = f"{m.pct_of_target:.1f}%" if m.pct_of_target is not None else "n/a"
        arrow = "up" if m.direction == "increase" else "down"
        lines.append(
            f"| {m.metric_name} | {m.target} ({arrow}, {m.window_days}d) "
            f"| {observed} | {pct} | {VERDICT_LABEL[m.verdict]} |"
        )
    lines += [
        "",
        "## What shipped",
        "",
        f"{release.name} shipped as version {release.version} on {release.ship_date}.",
        "",
        "## Learnings",
        "",
        "- What did the data confirm about the hypothesis?",
        "- What surprised us?",
        "- What will we do differently in the next release?",
        "",
        "_Generated by release_mgmt._",
    ]
    return "\n".join(lines)


def write_report(path: str, text: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
